apiVersion: v1
data:
  access-key: MVk5MjBCS0MwU0FXUE5ERThSRDY=
  secret-key: U25LTVFiSjhtUktWYm9QRHlta1lGYUZUejdWQnh5c3JzV3dKUm9NRA==
kind: Secret
metadata:
  creationTimestamp: "2026-03-17T11:58:52Z"
  name: s3-credentials
  namespace: stenc-ns
  resourceVersion: "4255945309"
  uid: 061dd02a-f606-43ab-a789-2e114e72687c
type: Opaque
