apiVersion: v1
kind: Pod
metadata:
  name: pollen-train-test-pod
  namespace: stenc-ns
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: train-worker
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      image: ttl.sh/pollen-train-825ffb72:24h
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          echo "Test pod"
          sleep 3600
      resources:
        limits:
          nvidia.com/gpu: 1
          memory: "32Gi"
          cpu: "8"
        requests:
          nvidia.com/gpu: 1
          memory: "16Gi"
          cpu: "4"
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "16Gi"
  restartPolicy: Never
