apiVersion: batch/v1
kind: Job
metadata:
  name: wipe-s3-fast
  namespace: stenc-ns
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: wipe
          image: ttl.sh/pollen-species-builder:v2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          command:
            - sh
            - -c
            - |
              echo "Wiping Trainig_data from S3..."
              s5cmd --endpoint-url "$S3_ENDPOINT" --no-verify-ssl rm "s3://$S3_BUCKET/PEG/Colorado/Species_model/Trainig_data/*"
          env:
            - name: S3_ENDPOINT
              value: "https://s3.cl4.du.cesnet.cz"
            - name: S3_BUCKET
              value: "bucket"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret-key
      restartPolicy: Never
