import os
import argparse
from ultralytics import YOLO
from datetime import datetime

MODEL_DIR = "/home/meow/Documents/Antigravity/Colorado_pollen_detection/models/species_classifier"
GENERAL_MODEL_LATEST = "/home/meow/Documents/Antigravity/Colorado_pollen_detection/models/general_pollen/latest.pt"

def train_species(dataset_yaml):
    os.makedirs(MODEL_DIR, exist_ok=True)
    run_name = f"species_classifier_{datetime.now().strftime('%Y%m%d_%H%M')}"
    
    print(f"🚀 Training {run_name} on Species Classification...")
    
    # Check if the general model exists
    if os.path.exists(GENERAL_MODEL_LATEST):
        print(f"   Using existing general pollen model as base: {GENERAL_MODEL_LATEST}")
        base_weights = GENERAL_MODEL_LATEST
    else:
        print("⚠️ General pollen model (latest.pt) not found! Defaulting to yolov8n.pt")
        base_weights = "yolov8n.pt"

    model = YOLO(base_weights) 
    
    results = model.train(
        data=dataset_yaml,
        epochs=100,
        patience=0,
        close_mosaic=20,
        batch=16,
        imgsz=640,
        project=MODEL_DIR,
        name=run_name,
        # Standard augmentations for species classification
        degrees=10.0,
        translate=0.1,
        scale=0.5,
        mosaic=1.0,
        flipud=0.5,
        fliplr=0.5
    )
    
    actual_save_dir = results.save_dir
    best_weights = os.path.join(actual_save_dir, "weights", "best.pt")
    
    # Symlink to latest
    latest_link = os.path.join(MODEL_DIR, "latest.pt")
    if os.path.lexists(latest_link):
        os.remove(latest_link)
    if os.path.exists(best_weights):
        os.symlink(best_weights, latest_link)
        print(f"✅ Training completed! Latest species model linked at: {latest_link}")
    else:
        print("⚠️ Training completed but could not find best.pt!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train the specific species classifier.")
    parser.add_argument("--data", required=True, help="Path to data.yaml generated by the detection script")
    args = parser.parse_args()
    train_species(args.data)
